package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.VoltageSensor;
import com.qualcomm.robotcore.util.ElapsedTime;

import org.firstinspires.ftc.robotcore.external.navigation.CurrentUnit;

@TeleOp(name = "FlyWheelPIDTester", group = "test")
public class FlyWheelPIDTester extends OpMode {
    private final ElapsedTime timer = new ElapsedTime();
    private VoltageSensor voltageSensor;
    private double controlHubVoltage = 0;

    private Datalogger datalogger;
    private String datalogFilename = "FlyWheelPIDTester";   // modify name for each run

    private FlyWheel flyWheel = new FlyWheel();
    // Use this one to test built-in PIDF values
    private DcMotorEx flyWheelMotor;

    private double targetRPM = 400.0;

    private RunPIDFState runState = RunPIDFState.WAITING_TO_START;

    private enum RunPIDFState {
        WAITING_TO_START,
        RUN_ONE,
        QUICK_STOP,
        RUN_TWO,
        DELAYING_AFTER_RUNNING
    }

    @Override
    public void init() {
        voltageSensor = hardwareMap.get(VoltageSensor.class, "Control Hub");
        flyWheel.init(hardwareMap);
    }

    @Override
    public void loop() {

        telemetry.addData("Target RPM", targetRPM);
        telemetry.addData("RPM", flyWheel.getRPM());
        telemetry.update();
    }

    /*
     * The main state machine for running the PIDF test.
     * */
    private void runPIDFTest() {
        switch (runState) {
            case WAITING_TO_START:
                if (gamepad1.leftBumperWasPressed()) {
                    timer.reset();
                    flyWheel.setMotorPower(1);
                    runState = RunPIDFState.RUN_ONE;
                } else if (gamepad1.rightBumperWasPressed()) {
                    timer.reset();
                    flyWheel.setMotorPower(0);
                    runState = RunPIDFState.RUN_ONE;
                }
                break;

            // Start running the motor.
            case RUN_ONE:
                flyWheel.setRPM(targetRPM);
                if (timer.milliseconds() >= 1500) {
                    flyWheel.stopMotor();
                    timer.reset();
                    runState = RunPIDFState.QUICK_STOP;
                }
                logData();
                break;

            // Stop the motor to simulate launching or some other interruption.
            case QUICK_STOP:
                if (timer.milliseconds() >= 10) {
                    timer.reset();
                    runState = RunPIDFState.RUN_TWO;
                }
                logData();
                break;

            // Run the rest of the sequence.
            case RUN_TWO:
                flyWheel.setRPM(targetRPM);
                if (timer.milliseconds() >= 1500) {
                    flyWheelMotor.setPower(0);
                    timer.reset();
                    runState = RunPIDFState.DELAYING_AFTER_RUNNING;
                }
                logData();
                break;

            case DELAYING_AFTER_RUNNING:
                // Give some time for the motor to stop.
                if (timer.milliseconds() >= 300) {
                    datalogger.closeDataLogger();
                    runState = RunPIDFState.WAITING_TO_START;
                }
                logData();
                break;

            default:
                break;
        }
    }

    /*
     * Initialize the datalogger by naming the fields (column labels).
     * */
    private void initDatalogger() {
        // Name the fields (column labels) generated by this OpMode.
        datalogger.addField("Target RPM");
        datalogger.addField("Velocity");
        datalogger.addField("Current (mA)");
        datalogger.addField("Voltage (V)");
        datalogger.firstLine();                        // end first line (row)
    }

    /*
     * Log data to the datalogger when isRunning = true.
     * */
    private void logData() {
        datalogger.addField(targetRPM);
        datalogger.addField(flyWheel.getTicksPerSecond());
        datalogger.addField(flyWheel.flyWheelMotor.getCurrent(CurrentUnit.MILLIAMPS));
        datalogger.addField(controlHubVoltage);
        datalogger.newLine();
    }

}


