package org.firstinspires.ftc.teamcode;

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.TeleOp;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.VoltageSensor;
import com.qualcomm.robotcore.util.ElapsedTime;

import org.firstinspires.ftc.robotcore.external.navigation.CurrentUnit;

@TeleOp(name = "FlyWheelPIDTester", group = "test")
public class FlyWheelPIDTester extends OpMode {
    private final ElapsedTime timer = new ElapsedTime();
    private VoltageSensor voltageSensor;
    private double controlHubVoltage = 0;
    private double motorCurrent = 0;

    private Datalogger datalogger;
    private String datalogFilename = "FlyWheelPIDTester";   // modify name for each run

    private FlyWheel flyWheel;
    // Use this one to test built-in PIDF values
    private DcMotorEx flyWheelMotor;

    private double targetRPM = 400.0;

    private RunPIDFState runState = RunPIDFState.WAITING_TO_START;

    private enum RunPIDFState {
        WAITING_TO_START,
        RUN_ONE,
        QUICK_STOP,
        RUN_TWO,
        DELAYING_AFTER_RUNNING
    }

    @Override
    public void init() {
        voltageSensor = hardwareMap.get(VoltageSensor.class, "Control Hub");
        flyWheel = new FlyWheel(FlyWheel.PIDFType.SDK_DEFAULT);
    }

    @Override
    public void init_loop() {
        // Select the PIDF type to test.
        if (gamepad1.dpadUpWasPressed()) {
            flyWheel.pidfType = flyWheel.pidfType.getNext();
        }

        telemetry.addLine("dpad Up toggles PIDF Type");
        telemetry.addData("PIDF Type", flyWheel.pidfType);
        telemetry.addLine("Press start to run the PIDF test.");
        telemetry.update();
    }

    @Override
    public void start() {
        flyWheel.init(hardwareMap);
        datalogFilename = String.format("%s%s", datalogFilename, flyWheel.pidfType);
        datalogger = new Datalogger(datalogFilename);
        initDatalogger();
        timer.reset();
    }

    @Override
    public void loop() {
        runPIDFTest();

        telemetry.addData("PIDF Type", flyWheel.pidfType);
        telemetry.addData("Run state", runState);
        telemetry.addData("Current (mA)",
                "%6.2f", flyWheel.flyWheelMotor.getCurrent(CurrentUnit.MILLIAMPS));
        telemetry.addData("Voltage", "%6.2f", controlHubVoltage);
        telemetry.addData("Target RPM", targetRPM);
        telemetry.addData("RPM", flyWheel.getRPM());
        telemetry.update();
    }

    /*
     * The main state machine for running the PIDF test.
     * */
    private void runPIDFTest() {
        controlHubVoltage = voltageSensor.getVoltage();
        motorCurrent = flyWheel.flyWheelMotor.getCurrent(CurrentUnit.MILLIAMPS);
        switch (runState) {
            case WAITING_TO_START:
                if (gamepad1.startWasPressed()) {
                    timer.reset();
                    flyWheel.stopMotor();
                    runState = RunPIDFState.RUN_ONE;
                }
                break;

            // Start running the motor.
            case RUN_ONE:
                flyWheel.setRPM(targetRPM);
                if (timer.milliseconds() >= 1500) {
                    flyWheel.stopMotor();
                    timer.reset();
                    runState = RunPIDFState.QUICK_STOP;
                }
                logData();
                break;

            // Stop the motor to simulate launching or some other interruption.
            case QUICK_STOP:
                if (timer.milliseconds() >= 100) {
                    timer.reset();
                    runState = RunPIDFState.RUN_TWO;
                }
                logData();
                break;

            // Run the rest of the sequence.
            case RUN_TWO:
                flyWheel.setRPM(targetRPM);
                if (timer.milliseconds() >= 1500) {
                    flyWheel.stopMotor();
                    timer.reset();
                    runState = RunPIDFState.DELAYING_AFTER_RUNNING;
                }
                logData();
                break;

            case DELAYING_AFTER_RUNNING:
                // Give some time for the motor to stop.
                if (timer.milliseconds() >= 600) {
                    datalogger.closeDataLogger();
                    runState = RunPIDFState.WAITING_TO_START;
                }
                logData();
                break;

            default:
                break;
        }
    }

    /*
     * Initialize the datalogger by naming the fields (column labels).
     * */
    private void initDatalogger() {
        // Name the fields (column labels) generated by this OpMode.
        datalogger.addField("Target RPM");
        datalogger.addField("RPM");
        datalogger.addField("Velocity");
        datalogger.addField("Current (mA)");
        datalogger.addField("Voltage (V)");
        datalogger.firstLine();                        // end first line (row)
    }

    /*
     * Log data to the datalogger when isRunning = true.
     * */
    private void logData() {
        datalogger.addField(targetRPM);
        datalogger.addField(flyWheel.getRPM());
        datalogger.addField(flyWheel.getTicksPerSecond());
        datalogger.addField(motorCurrent);
        datalogger.addField(controlHubVoltage);
        datalogger.newLine();
    }

}


